export const posts = [
  {
    _id: "1",
    name: "John Doe",
    picture: "https://randomuser.me/api/portraits/men/1.jpg",
    post_at: "2025-06-18T09:30:00Z",
    post_type: "public",
    post_msg:
      "Excited to start my new job today! loLorem ipsum dolor sit amet consectetur adipisicing elit. Fuga qui accusamus nesciunt modi quasi dignissimos, aliquam quo? Sit eveniet nisi aliquam tempora sequi? Voluptatum sapiente hic quasi unde. Fugit, tempore.",
    post_img:
      "https://images.pexels.com/photos/32438401/pexels-photo-32438401.jpeg",
    like: 34,
    comment: 5,
    share: 2,
  },
  {
    _id: "2",
    name: "Jane Smith",
    picture: "https://randomuser.me/api/portraits/women/2.jpg",
    post_at: "2025-06-17T15:45:00Z",
    post_type: "public",
    post_msg: "A beautiful sunset at the beach 🌅",
    post_img:
      "https://images.pexels.com/photos/21077130/pexels-photo-21077130.jpeg",
    like: 120,
    comment: 14,
    share: 10,
  },
  {
    _id: "3",
    name: "Amit Raj",
    picture: "https://randomuser.me/api/portraits/men/3.jpg",
    post_at: "2025-06-17T10:12:00Z",
    post_type: "public",
    post_msg: "JavaScript or Python – what’s your pick for backend?",
    post_img:
      "https://images.pexels.com/photos/32585052/pexels-photo-32585052.jpeg",
    like: 57,
    comment: 22,
    share: 3,
  },
  {
    _id: "4",
    name: "Lisa Wang",
    picture: "https://randomuser.me/api/portraits/women/4.jpg",
    post_at: "2025-06-16T08:00:00Z",
    post_type: "public",
    post_msg: "My latest artwork 🎨🖌️",
    post_img:
      "https://images.pexels.com/photos/32607286/pexels-photo-32607286.jpeg",
    like: 95,
    comment: 10,
    share: 6,
  },
  {
    _id: "5",
    name: "Mohammad Asif",
    picture: "https://randomuser.me/api/portraits/men/5.jpg",
    post_at: "2025-06-15T19:30:00Z",
    post_type: "public",
    post_msg: "Just deployed my first MERN stack project!",
    post_img:
      "https://images.pexels.com/photos/32535462/pexels-photo-32535462.jpeg",
    like: 89,
    comment: 16,
    share: 12,
  },
  {
    _id: "6",
    name: "Emily Johnson",
    picture: "https://randomuser.me/api/portraits/women/6.jpg",
    post_at: "2025-06-14T13:20:00Z",
    post_type: "public",
    post_msg: "Nature walk this weekend 🌲🌼",
    post_img:
      "https://images.pexels.com/photos/31203090/pexels-photo-31203090.jpeg",
    like: 66,
    comment: 7,
    share: 5,
  },
  {
    _id: "7",
    name: "Carlos Mendes",
    picture: "https://randomuser.me/api/portraits/men/7.jpg",
    post_at: "2025-06-14T07:45:00Z",
    post_type: "public",
    post_msg: "Coffee first, then code ☕💻",
    post_img:
      "https://images.pexels.com/photos/1912176/pexels-photo-1912176.jpeg",
    like: 40,
    comment: 3,
    share: 0,
  },
  {
    _id: "8",
    name: "Sarah Connor",
    picture: "https://randomuser.me/api/portraits/women/8.jpg",
    post_at: "2025-06-13T21:15:00Z",
    post_type: "public",
    post_msg: "Throwback to last winter ❄️",
    post_img:
      "https://images.pexels.com/photos/30135244/pexels-photo-30135244.jpeg",
    like: 102,
    comment: 9,
    share: 4,
  },
  {
    _id: "9",
    name: "Dev Patel",
    picture: "https://randomuser.me/api/portraits/men/9.jpg",
    post_at: "2025-06-13T18:00:00Z",
    post_type: "public",
    post_msg: "What's your favorite programming quote?",
    post_img:
      "https://images.pexels.com/photos/32455921/pexels-photo-32455921.jpeg",
    like: 28,
    comment: 12,
    share: 1,
  },
  {
    _id: "10",
    name: "Nina Kapoor",
    picture: "https://randomuser.me/api/portraits/women/10.jpg",
    post_at: "2025-06-12T16:30:00Z",
    post_type: "public",
    post_msg: "Homemade pizza night 🍕❤️",
    post_img:
      "https://images.pexels.com/photos/3701434/pexels-photo-3701434.jpeg",
    like: 130,
    comment: 18,
    share: 8,
  },
];
